# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:5.5.0

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
# RUN elasticsearch-plugin uninstall ingest-geoip
# RUN elasticsearch-plugin uninstall ingest-user-agent
# RUN elasticsearch-plugin install ingest-geoip
# RUN elasticsearch-plugin install ingest-user-agent
# RUN elasticsearch-plugin install license

# RUN elasticsearch-plugin remove x-pack
# RUN elasticsearch-plugin remove shield
# RUN elasticsearch-plugin install x-pack
# RUN elasticsearch-plugin install license
# RUN elasticsearch-plugin install shield


